### ISSUE TITLE
 Add link to open image in new tab to view in full size

### ISSUE THREAD

**Issue by asfaltboy** [simonbrowndotje/c4model#10]
Some of the images are high detail, and when embedded on a page the text may appear a bit small, which require opening the underlying URL in a separate tab to view full size.

The simplest way to help individuals who want to quickly examine diagram details, is to allow them to click and open it in a new tab, then zoom in as needed, and then close the tab when done.

As a stretch goal, we can use a "light-box"-like library. I've used [magnific-popup][1] in the past for this.

[1]: https://dimsemenov.com/plugins/magnific-popup/

**Comment by simonbrowndotje** [comment]
Most of the images do open when clicked upon - which ones are missing?

**Comment by asfaltboy** [comment]
Ah you are right, sorry I made this assumption when looking at a specific page, and didn't check other pages. The pages I noticed missing links to images are:
- https://c4model.com/introduction
- https://c4model.com/abstractions/microservices

We can probably run a `grep -B3 img` to double check if there are any other missing links.
