### ISSUE TITLE
structurizr diagram DSL for diagram examples

### ISSUE THREAD

**Issue by Gordrin** [simonbrowndotje/c4model#12]
Hi thank you very much for the amazing work with structurizr and the c4 model. 
Would it be possible to add the dsl used to generate the images of the website to this repository/website.

I think that could help getting into the diagramming with it. 

I see that you want to keep the tooling out for reasons but as you are involved into structurizr and created the diagrams using it, have them as examples at least in the repository could help newbies of structurizr getting into it.

**Comment by simonbrowndotje** [comment]
Which examples are you looking for?

**Comment by Gordrin** [comment]
For example the Microservice one. Because there are different shapes and colors. I didn't found a example in structurizr how to apply the templates to change the shapes to hexagonal or database.

**Comment by simonbrowndotje** [comment]
That particular example will be available via the [Structurizr Patreon](https://www.patreon.com/structurizr) at some point soon. A similar example is available on the [DSL demo page](https://structurizr.com/dsl?example=microservices) and [examples repo](https://github.com/structurizr/examples) though.

**Comment by Gordrin** [comment]
Oh well I must have been blind when I searched for some examples like that. Thank you for the links. That's quite helpful as I want dig deeper documenting architecture using structurizr as it's an awesome tooling.
